/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/register": {
    /**
     * Register
     * @description 新規ユーザー登録
     */
    post: operations["register_api_v1_auth_register_post"];
  };
  "/api/v1/auth/login": {
    /**
     * Login
     * @description ユーザーログイン
     */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/auth/me": {
    /**
     * Get Me
     * @description 現在のユーザー情報を取得
     */
    get: operations["get_me_api_v1_auth_me_get"];
  };
  "/api/v1/logs/": {
    /**
     * List Logs
     * @description ログ一覧を取得（自分のログのみ）
     * タイムラインビュー用
     */
    get: operations["list_logs_api_v1_logs__get"];
    /**
     * Create Log
     * @description 新しいログを作成
     *
     * ノン・ジャッジメンタル応答:
     * AIは「回答」や「アドバイス」を行わない。
     * 「聞く」ことに徹し、受容的な相槌（Ack）のみを返す。
     */
    post: operations["create_log_api_v1_logs__post"];
  };
  "/api/v1/logs/{log_id}": {
    /**
     * Get Log
     * @description 特定のログを取得
     */
    get: operations["get_log_api_v1_logs__log_id__get"];
    /**
     * Delete Log
     * @description ログを削除
     */
    delete: operations["delete_log_api_v1_logs__log_id__delete"];
  };
  "/api/v1/logs/calendar/{year}/{month}": {
    /**
     * Get Logs By Month
     * @description カレンダービュー用: 月別のログ日付リスト
     */
    get: operations["get_logs_by_month_api_v1_logs_calendar__year___month__get"];
  };
  "/api/v1/logs/transcribe": {
    /**
     * Transcribe Audio
     * @description 音声ファイルをWhisper APIで文字起こしし、ログとして保存
     *
     * - 音声ファイルを受け取り、OpenAI Whisper APIで文字起こし
     * - 文字起こし結果をログとして保存
     * - Context Analyzer と Structural Analyzer を実行
     */
    post: operations["transcribe_audio_api_v1_logs_transcribe_post"];
  };
  "/api/v1/conversation/": {
    /**
     * Converse
     * @description 会話エンドポイント: LangGraphで意図を分類し、適切なノードで応答を生成
     *
     * リクエスト: {"message": "...", "mode_override": "empathy" (optional), "research_approved": false}
     * - 自動モード: messageからAIが意図を判定して最適なノードへルーティング
     * - 手動モード: mode_overrideで意図を強制指定（/vent, /idea 等のスラッシュコマンド対応）
     * - Deep Research: research_approved=true でリサーチ実行
     *
     * レスポンスには以下が含まれる:
     * - response: AIの即時回答
     * - intent_badge: 判定されたインテント情報（UI表示用）
     * - background_task: 非同期タスク情報（Shadow Reply用、knowledgeノード時のみ）
     * - requires_research_consent: Deep Research 提案フラグ
     */
    post: operations["converse_api_v1_conversation__post"];
  };
  "/api/v1/insights/": {
    /**
     * List Insights
     * @description 公開インサイト一覧を取得
     * 誰でも閲覧可能（認証オプショナル）
     */
    get: operations["list_insights_api_v1_insights__get"];
  };
  "/api/v1/insights/my": {
    /**
     * List My Insights
     * @description 自分のインサイト一覧を取得
     */
    get: operations["list_my_insights_api_v1_insights_my_get"];
  };
  "/api/v1/insights/pending": {
    /**
     * Get Pending Proposals
     * @description 承認待ちの共有提案を取得
     * Sharing Broker からの提案
     */
    get: operations["get_pending_proposals_api_v1_insights_pending_get"];
  };
  "/api/v1/insights/decide": {
    /**
     * Decide Sharing
     * @description 共有の承認/拒否を決定
     */
    post: operations["decide_sharing_api_v1_insights_decide_post"];
  };
  "/api/v1/insights/{insight_id}": {
    /**
     * Get Insight
     * @description インサイト詳細を取得
     */
    get: operations["get_insight_api_v1_insights__insight_id__get"];
  };
  "/api/v1/insights/{insight_id}/thanks": {
    /**
     * Send Thanks
     * @description インサイトに「ありがとう」を送る
     * フィードバック機能
     */
    post: operations["send_thanks_api_v1_insights__insight_id__thanks_post"];
  };
  "/api/v1/recommendations/": {
    /**
     * Get Recommendations
     * @description 入力中のテキストに基づいて関連インサイトを取得
     *
     * Serendipity Matcher による「副作用的」レコメンデーション
     * - ユーザーが「検索」する前に関連情報を提示
     * - 入力中/入力直後にトリガー
     */
    post: operations["get_recommendations_api_v1_recommendations__post"];
  };
  "/api/v1/recommendations/similar/{insight_id}": {
    /**
     * Get Similar Insights
     * @description 特定のインサイトに類似するインサイトを取得
     * グラフ接続による関連知見の探索
     */
    get: operations["get_similar_insights_api_v1_recommendations_similar__insight_id__get"];
  };
  "/": {
    /**
     * Root
     * @description ルートエンドポイント
     */
    get: operations["root__get"];
  };
  "/health": {
    /**
     * Health Check
     * @description ヘルスチェックエンドポイント
     */
    get: operations["health_check_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AckResponse
     * @description ノン・ジャッジメンタル応答
     * 「聞く」ことに徹した受容的な相槌 + 会話ラリー用の自然言語返答
     */
    AckResponse: {
      /** Message */
      message: string;
      /**
       * Log Id
       * Format: uuid
       */
      log_id: string;
      /**
       * Thread Id
       * Format: uuid
       */
      thread_id: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Transcribed Text */
      transcribed_text?: string | null;
      /**
       * Skip Structural Analysis
       * @default false
       */
      skip_structural_analysis?: boolean;
      /** Conversation Reply */
      conversation_reply?: string | null;
      /**
       * Requires Research Consent
       * @default false
       */
      requires_research_consent?: boolean;
      /** Research Log Id */
      research_log_id?: string | null;
    };
    /**
     * BackgroundTask
     * @description 非同期バックグラウンドタスクの情報
     */
    BackgroundTask: {
      /** Task Id */
      task_id: string;
      /** Task Type */
      task_type: string;
      /**
       * Status
       * @default queued
       * @enum {string}
       */
      status?: "queued" | "running" | "completed" | "failed";
      /**
       * Message
       * @description ユーザーに表示するメッセージ
       */
      message: string;
      /**
       * Result Log Id
       * @description 結果が保存される RawLog の ID（ポーリング用）
       */
      result_log_id?: string | null;
    };
    /** Body_transcribe_audio_api_v1_logs_transcribe_post */
    Body_transcribe_audio_api_v1_logs_transcribe_post: {
      /**
       * Audio
       * Format: binary
       */
      audio: string;
      /** Thread Id */
      thread_id?: string | null;
    };
    /**
     * ConversationIntent
     * @description 会話の意図分類
     * @enum {string}
     */
    ConversationIntent: "chat" | "empathy" | "knowledge" | "deep_dive" | "brainstorm" | "probe" | "state_share";
    /**
     * ConversationRequest
     * @description 会話リクエスト
     */
    ConversationRequest: {
      /**
       * Message
       * @description ユーザー入力テキスト
       */
      message: string;
      /** @description モード強制上書き（Mode Switcher機能） */
      mode_override?: components["schemas"]["ConversationIntent"] | null;
      /**
       * Research Approved
       * @description Deep Research の提案フェーズを開始する場合 True
       * @default false
       */
      research_approved?: boolean;
      /**
       * Research Plan Confirmed
       * @description 調査計画書を確認済みで実行を開始する場合 True
       * @default false
       */
      research_plan_confirmed?: boolean;
      /**
       * Research Plan
       * @description 確認済みの調査計画書データ
       */
      research_plan?: {
        [key: string]: unknown;
      } | null;
      /**
       * Thread Id
       * @description 会話スレッドID（Deep Research 結果の保存先特定に使用）
       */
      thread_id?: string | null;
    };
    /**
     * ConversationResponse
     * @description 会話レスポンス
     */
    ConversationResponse: {
      /**
       * Response
       * @description AIの即時回答
       */
      response: string;
      /** @description 判定されたインテントバッジ */
      intent_badge: components["schemas"]["IntentBadge"];
      /**
       * Background Task Info
       * @description Deep Research等のノードから直接返却されるタスク情報
       */
      background_task_info?: {
        [key: string]: unknown;
      } | null;
      /** @description 非同期タスク情報（Shadow Reply用） */
      background_task?: components["schemas"]["BackgroundTask"] | null;
      /** User Id */
      user_id: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp?: string;
      /**
       * Requires Research Consent
       * @description Deep Research の提案が含まれている場合 True
       * @default false
       */
      requires_research_consent?: boolean;
      /**
       * Is Researching
       * @description Deep Research が非同期実行中の場合 True
       * @default false
       */
      is_researching?: boolean;
      /** @description 調査計画書（ユーザー確認待ち） */
      research_plan?: components["schemas"]["ResearchPlan"] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * InsightCardListResponse
     * @description インサイトリストレスポンス
     */
    InsightCardListResponse: {
      /** Items */
      items: components["schemas"]["InsightCardResponse"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
    };
    /**
     * InsightCardResponse
     * @description インサイトレスポンススキーマ
     */
    InsightCardResponse: {
      /** Title */
      title: string;
      /** Context */
      context?: string | null;
      /** Problem */
      problem?: string | null;
      /** Solution */
      solution?: string | null;
      /** Summary */
      summary: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Author Id
       * Format: uuid
       */
      author_id: string;
      /** Topics */
      topics?: string[] | null;
      /** Tags */
      tags?: string[] | null;
      /** Sharing Value Score */
      sharing_value_score: number;
      status: components["schemas"]["InsightStatus"];
      /** View Count */
      view_count: number;
      /** Thanks Count */
      thanks_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Published At */
      published_at?: string | null;
    };
    /**
     * InsightStatus
     * @description インサイトの状態
     * @enum {string}
     */
    InsightStatus: "draft" | "pending_approval" | "approved" | "rejected";
    /**
     * IntentBadge
     * @description Intent Badge - ルーターの判定結果を可視化
     */
    IntentBadge: {
      intent: components["schemas"]["ConversationIntent"];
      /** Confidence */
      confidence: number;
      /**
       * Label
       * @description UIに表示するラベル
       */
      label: string;
      /**
       * Icon
       * @description UIに表示するアイコン識別子
       */
      icon: string;
    };
    /**
     * LogIntent
     * @description ユーザーの意図分類
     * - LOG: 単に記録したい
     * - VENT: 愚痴を言いたい
     * - STRUCTURE: 整理したい
     * - STATE: コンディション・状態記録
     * - DEEP_RESEARCH: AIによる能動的な調査・リサーチ
     * @enum {string}
     */
    LogIntent: "log" | "vent" | "structure" | "state" | "deep_research";
    /**
     * RawLogCreate
     * @description ログ作成スキーマ
     */
    RawLogCreate: {
      /** Content */
      content: string;
      /**
       * Content Type
       * @default text
       */
      content_type?: string;
      /** Thread Id */
      thread_id?: string | null;
    };
    /**
     * RawLogListResponse
     * @description ログリストレスポンス
     */
    RawLogListResponse: {
      /** Items */
      items: components["schemas"]["RawLogResponse"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
    };
    /**
     * RawLogResponse
     * @description ログレスポンススキーマ
     */
    RawLogResponse: {
      /** Content */
      content: string;
      /**
       * Content Type
       * @default text
       */
      content_type?: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Thread Id */
      thread_id?: string | null;
      intent?: components["schemas"]["LogIntent"] | null;
      /** Emotions */
      emotions?: string[] | null;
      /** Emotion Scores */
      emotion_scores?: {
        [key: string]: unknown;
      } | null;
      /** Topics */
      topics?: string[] | null;
      /** Tags */
      tags?: string[] | null;
      /** Metadata Analysis */
      metadata_analysis?: {
        [key: string]: unknown;
      } | null;
      /** Structural Analysis */
      structural_analysis?: {
        [key: string]: unknown;
      } | null;
      /** Assistant Reply */
      assistant_reply?: string | null;
      /** Is Analyzed */
      is_analyzed: boolean;
      /** Is Processed For Insight */
      is_processed_for_insight: boolean;
      /**
       * Is Structure Analyzed
       * @default false
       */
      is_structure_analyzed?: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * RecommendationItem
     * @description レコメンデーションアイテム
     */
    RecommendationItem: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /** Topics */
      topics: string[];
      /** Relevance Score */
      relevance_score: number;
      /** Preview */
      preview: string;
      /** Category */
      category?: string | null;
      /** Reason */
      reason?: string | null;
      /** Team Members */
      team_members?: components["schemas"]["TeamMember"][] | null;
      /** Project Name */
      project_name?: string | null;
    };
    /**
     * RecommendationRequest
     * @description レコメンデーションリクエスト
     */
    RecommendationRequest: {
      /** Current Input */
      current_input: string;
      /** Exclude Ids */
      exclude_ids?: string[] | null;
    };
    /**
     * RecommendationResponse
     * @description レコメンデーションレスポンス
     */
    RecommendationResponse: {
      /** Has Recommendations */
      has_recommendations: boolean;
      /** Recommendations */
      recommendations: components["schemas"]["RecommendationItem"][];
      /** Trigger Reason */
      trigger_reason: string;
      /** Display Message */
      display_message?: string | null;
    };
    /**
     * ResearchPlan
     * @description 調査計画書（Research Brief）
     */
    ResearchPlan: {
      /**
       * Title
       * @description 調査タイトル
       */
      title: string;
      /**
       * Topic
       * @description 具体的な調査主題
       */
      topic: string;
      /**
       * Scope
       * @description 対象範囲（地域・年代・分野など）
       */
      scope: string;
      /**
       * Perspectives
       * @description 調査の視点・切り口
       */
      perspectives: string[];
      /**
       * Sanitized Query
       * @description 個人情報を排除した検索クエリ
       */
      sanitized_query: string;
    };
    /**
     * SharingDecision
     * @description 共有判断スキーマ
     */
    SharingDecision: {
      /**
       * Insight Id
       * Format: uuid
       */
      insight_id: string;
      /** Approved */
      approved: boolean;
      /** Feedback */
      feedback?: string | null;
    };
    /**
     * SharingProposal
     * @description 共有提案スキーマ
     * Sharing Broker がユーザーに提示する
     */
    SharingProposal: {
      insight: components["schemas"]["InsightCardResponse"];
      /**
       * Message
       * @default あなたのこの経験は、チームの役に立つ可能性があります。この形式で共有しますか？
       */
      message?: string;
      /** Original Content Preview */
      original_content_preview?: string | null;
    };
    /**
     * TeamMember
     * @description チーム提案メンバー
     */
    TeamMember: {
      /** User Id */
      user_id: string;
      /** Display Name */
      display_name: string;
      /** Role */
      role: string;
      /** Avatar Url */
      avatar_url?: string | null;
    };
    /**
     * Token
     * @description JWTトークンレスポンス
     */
    Token: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
      user: components["schemas"]["UserResponse"];
    };
    /**
     * UserCreate
     * @description ユーザー作成スキーマ
     */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Display Name */
      display_name?: string | null;
      /** Password */
      password: string;
    };
    /**
     * UserLogin
     * @description ログインリクエストスキーマ
     */
    UserLogin: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * UserResponse
     * @description ユーザーレスポンススキーマ
     */
    UserResponse: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Display Name */
      display_name?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Avatar Url */
      avatar_url?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Is Verified */
      is_verified: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Register
   * @description 新規ユーザー登録
   */
  register_api_v1_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Login
   * @description ユーザーログイン
   */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserLogin"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Me
   * @description 現在のユーザー情報を取得
   */
  get_me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  /**
   * List Logs
   * @description ログ一覧を取得（自分のログのみ）
   * タイムラインビュー用
   */
  list_logs_api_v1_logs__get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RawLogListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Log
   * @description 新しいログを作成
   *
   * ノン・ジャッジメンタル応答:
   * AIは「回答」や「アドバイス」を行わない。
   * 「聞く」ことに徹し、受容的な相槌（Ack）のみを返す。
   */
  create_log_api_v1_logs__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RawLogCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["AckResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Log
   * @description 特定のログを取得
   */
  get_log_api_v1_logs__log_id__get: {
    parameters: {
      path: {
        log_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RawLogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Log
   * @description ログを削除
   */
  delete_log_api_v1_logs__log_id__delete: {
    parameters: {
      path: {
        log_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Logs By Month
   * @description カレンダービュー用: 月別のログ日付リスト
   */
  get_logs_by_month_api_v1_logs_calendar__year___month__get: {
    parameters: {
      path: {
        year: number;
        month: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Transcribe Audio
   * @description 音声ファイルをWhisper APIで文字起こしし、ログとして保存
   *
   * - 音声ファイルを受け取り、OpenAI Whisper APIで文字起こし
   * - 文字起こし結果をログとして保存
   * - Context Analyzer と Structural Analyzer を実行
   */
  transcribe_audio_api_v1_logs_transcribe_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_transcribe_audio_api_v1_logs_transcribe_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["AckResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Converse
   * @description 会話エンドポイント: LangGraphで意図を分類し、適切なノードで応答を生成
   *
   * リクエスト: {"message": "...", "mode_override": "empathy" (optional), "research_approved": false}
   * - 自動モード: messageからAIが意図を判定して最適なノードへルーティング
   * - 手動モード: mode_overrideで意図を強制指定（/vent, /idea 等のスラッシュコマンド対応）
   * - Deep Research: research_approved=true でリサーチ実行
   *
   * レスポンスには以下が含まれる:
   * - response: AIの即時回答
   * - intent_badge: 判定されたインテント情報（UI表示用）
   * - background_task: 非同期タスク情報（Shadow Reply用、knowledgeノード時のみ）
   * - requires_research_consent: Deep Research 提案フラグ
   */
  converse_api_v1_conversation__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConversationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ConversationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Insights
   * @description 公開インサイト一覧を取得
   * 誰でも閲覧可能（認証オプショナル）
   */
  list_insights_api_v1_insights__get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        topic?: string | null;
        tag?: string | null;
        search?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InsightCardListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List My Insights
   * @description 自分のインサイト一覧を取得
   */
  list_my_insights_api_v1_insights_my_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        status_filter?: components["schemas"]["InsightStatus"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InsightCardListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Pending Proposals
   * @description 承認待ちの共有提案を取得
   * Sharing Broker からの提案
   */
  get_pending_proposals_api_v1_insights_pending_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SharingProposal"][];
        };
      };
    };
  };
  /**
   * Decide Sharing
   * @description 共有の承認/拒否を決定
   */
  decide_sharing_api_v1_insights_decide_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SharingDecision"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InsightCardResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Insight
   * @description インサイト詳細を取得
   */
  get_insight_api_v1_insights__insight_id__get: {
    parameters: {
      path: {
        insight_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InsightCardResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Send Thanks
   * @description インサイトに「ありがとう」を送る
   * フィードバック機能
   */
  send_thanks_api_v1_insights__insight_id__thanks_post: {
    parameters: {
      path: {
        insight_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Recommendations
   * @description 入力中のテキストに基づいて関連インサイトを取得
   *
   * Serendipity Matcher による「副作用的」レコメンデーション
   * - ユーザーが「検索」する前に関連情報を提示
   * - 入力中/入力直後にトリガー
   */
  get_recommendations_api_v1_recommendations__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecommendationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RecommendationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Similar Insights
   * @description 特定のインサイトに類似するインサイトを取得
   * グラフ接続による関連知見の探索
   */
  get_similar_insights_api_v1_recommendations_similar__insight_id__get: {
    parameters: {
      query?: {
        limit?: number;
      };
      path: {
        insight_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Root
   * @description ルートエンドポイント
   */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Health Check
   * @description ヘルスチェックエンドポイント
   */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
